### ISSUE TITLE
Can't use the device list

### ISSUE THREAD

**Issue by martin67** [svrooij/node-xiaomi2mqtt#4]
I get an error when I try to include a list of devices:

```
martin@mahler:~$ xiaomi2mqtt -d /etc/xiaomi2mqtt.conf`
2017-11-24 10:46:16.793 <info>  xiaomi2mqtt 1.0.0 starting
2017-11-24 10:46:16.850 <info>  Loading devices from: /etc/xiaomi2mqtt.conf
/etc/xiaomi2mqtt.conf:2
  "device_id": "Nice name",
             ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at fs.access (/usr/local/lib/node_modules/xiaomi2mqtt/src/bridge.js:21:19)
martin@mahler:~$
```

The file looks like this:
```
{
  "device_id": "Nice name",
  "158d00016c8dfb": "Sovrum",
  "158d0001b8f5ed": "Ivars rum",
  "158d0001ddae03": "Märtas rum",
  "158d00019cb8ff": "Nils rum",
  "158d0001c03460": "Källartrapp",
  "158d00018b39c4": "TV"
}
```
Everything else works fine (when I don't include the file)

**Comment by soundman666** [comment]
You need to rename file xiaomi2mqtt.conf to xiaomi2mqtt.json

**Comment by ghasemikasra39** [comment]
Would it be alright if you explain the xiaomi2mqtt.json file? 
The question is asked here:
https://stackoverflow.com/questions/52269938/how-is-xiaomi2mqtt-connected-to-aquara-hardware-device

**Comment by svrooij** [comment]
This question is pretty unrelated to this issue. Please check out the [wiki](https://github.com/svrooij/node-xiaomi2mqtt/wiki)
